name: example
description: An example application for the currency_picker package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.13.0 <4.0.0'
  flutter: '>=3.47.0'

dependencies:
  currency_picker:
    path: ../
  flutter:
    sdk: flutter
  material_ui: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
